apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karpenter
  namespace: karpenter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: karpenter
      app.kubernetes.io/instance: karpenter
  endpoints:
  - port: http-metrics
    path: /metrics
  namespaceSelector:
    matchNames:
      - karpenter
---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: cluster-autoscaler
#   namespace: kube-system
#   labels:
#     release: prometheus
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/name: aws-cluster-autoscaler
#       app.kubernetes.io/instance: cluster-autoscaler
#   endpoints:
#   - port: http
#     path: /metrics
#   namespaceSelector:
#     matchNames:
#       - kube-system
